version: '3'

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chatbot
      - POSTGRES_PASSWORD=chatbot
      - POSTGRES_DB=chatbot
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: