version: '3.7'
services:
  web:
    image: pac1f1c/shaman
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shaman/:/usr/src/shaman/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shaman
      - POSTGRES_PASSWORD=shaman
      - POSTGRES_DB=shaman
volumes:
  postgres_data:
